/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.screen;

import br.course.Course;
import br.course.CourseDAO;
import br.meal.Meal;
import br.meal.MealDAO;
import br.shift.Shift;
import br.shift.ShiftDAO;
import br.user.User;
import br.user.UserDAO;
import br.util.UserActive;
import br.util.Util;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.hibernate.Hibernate;

/**
 *
 * @author pelusb
 */
public class ChangePasswordFrm extends javax.swing.JDialog {

    private Shift shift;
    private List<Meal> meals;

    /**
     * Creates new form RegisterStudent
     */
    public ChangePasswordFrm() {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setTitle("Mudar senha");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        tfPassNew = new javax.swing.JPasswordField();
        tfPassBefore = new javax.swing.JPasswordField();
        tfConfirmPassNew = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSave.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/Save_37110.png"))); // NOI18N
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        btCancel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/forceexit_103817.png"))); // NOI18N
        btCancel.setToolTipText("");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        tfPassNew.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfPassNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPassNewKeyPressed(evt);
            }
        });
        getContentPane().add(tfPassNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 330, 29));

        tfPassBefore.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfPassBefore.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPassBeforeKeyPressed(evt);
            }
        });
        getContentPane().add(tfPassBefore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 330, 29));

        tfConfirmPassNew.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfConfirmPassNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfConfirmPassNewKeyPressed(evt);
            }
        });
        getContentPane().add(tfConfirmPassNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 330, 29));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Confirmar nova senha: *");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Nova senha: *");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Senha anterior: *");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
        UserDAO uDAO = new UserDAO();
        User user = UserActive.retornaUsuarioAtivo();
        if (tfPassBefore.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe a senha anterior!",
                    "IFCE", JOptionPane.ERROR_MESSAGE);
            tfPassBefore.requestFocus();
            return;
        }
        if(!Util.md5(tfPassBefore.getText().toString()).equals(user.getSenha())){
            JOptionPane.showMessageDialog(rootPane, "Senha anterior incorreta!",
                    "IFCE", JOptionPane.ERROR_MESSAGE);
            tfPassBefore.requestFocus();
            return;
        }
        if (tfPassNew.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe a nova senha!",
                    "IFCE", JOptionPane.ERROR_MESSAGE);
            tfPassNew.requestFocus();
            return;
        }
        if (tfConfirmPassNew.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Confirme a nova senha!",
                    "IFCE", JOptionPane.ERROR_MESSAGE);
            tfConfirmPassNew.requestFocus();
            return;
        }
        if(!tfPassNew.getText().equals(tfConfirmPassNew.getText())){
            JOptionPane.showMessageDialog(rootPane, "Senha não confirmada!",
                    "IFCE", JOptionPane.ERROR_MESSAGE);
            tfConfirmPassNew.requestFocus();
            return;
        }
        
        
        
        user.setSenha(tfPassNew.getText());
        uDAO.update(user);
        JOptionPane.showMessageDialog(rootPane, "Senha alterada com sucesso!", "IFCE", 
                JOptionPane.INFORMATION_MESSAGE);
        setVisible(false);

    }//GEN-LAST:event_btSaveActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void tfPassNewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPassNewKeyPressed
       
    }//GEN-LAST:event_tfPassNewKeyPressed

    private void tfPassBeforeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPassBeforeKeyPressed
        
    }//GEN-LAST:event_tfPassBeforeKeyPressed

    private void tfConfirmPassNewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfConfirmPassNewKeyPressed
        
    }//GEN-LAST:event_tfConfirmPassNewKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePasswordFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField tfConfirmPassNew;
    private javax.swing.JPasswordField tfPassBefore;
    private javax.swing.JPasswordField tfPassNew;
    // End of variables declaration//GEN-END:variables
}
