/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.screen;

import br.allowsmd.StudentAllowMealDay;
import br.allowsmd.StudentAllowMealDayDAO;
import br.meal.Meal;
import br.meal.MealDAO;
import br.republic.ItensRepublic;
import br.republic.ItensRepublicDAO;
import br.util.UserActive;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author pelusb
 */
public class ItensRepublicFrmRegister extends javax.swing.JDialog {

    private ItensRepublic itensRepublic;
    /**
     * Creates new form RegisterStudent
     */
    public ItensRepublicFrmRegister() {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setTitle("Estudante da República");
        this.itensRepublic = new ItensRepublic();
    }
    
    public ItensRepublicFrmRegister(ItensRepublic itensRepublic) {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setTitle("Estudante da República ["+itensRepublic.getRepublic().getDescription()+"]");
        this.itensRepublic = itensRepublic;
        lblStudent.setText(itensRepublic.getStudent().getName());
        cbResponsability.setSelected(itensRepublic.isResponsability());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudent = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cbResponsability = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStudent.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblStudent.setText("Estudante");
        getContentPane().add(lblStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 17, 380, -1));

        btSave.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/Save_37110.png"))); // NOI18N
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/forceexit_103817.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        cbResponsability.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbResponsability.setText("É reponsável?");
        getContentPane().add(cbResponsability, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja inserir o estudante ["+itensRepublic.getStudent().getName()
                + "] na república [" + itensRepublic.getRepublic().getDescription() + "]?"
                + "\nOBS: Será adicionado permissão para todas as refeições.",
                    "Excluir República", JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
            //exclui permissoes
            StudentAllowMealDayDAO samDAO = new StudentAllowMealDayDAO();
            samDAO.executeSQL("delete from allowstudenmealday where student_id="+itensRepublic.getStudent().getId());
            
            //adiciona permissoes
            MealDAO mealDAL= new MealDAO();
            List<Meal> listMeal = mealDAL.checkExists("campus", UserActive.returnCampus());
            for(Meal meal : listMeal){
                StudentAllowMealDay saMealDay = new StudentAllowMealDay();
                saMealDay.setMeal(meal);
                saMealDay.setStudent(itensRepublic.getStudent());
                saMealDay.setMonday(true);
                saMealDay.setTuesday(true);
                saMealDay.setWednesday(true);
                saMealDay.setThursday(true);
                saMealDay.setFriday(true);
                saMealDay.setSaturday(false);
                samDAO.add(saMealDay);
            }



            itensRepublic.setResponsability(cbResponsability.isSelected());

            ItensRepublicDAO iDAO = new ItensRepublicDAO();
            if(itensRepublic.getId()==null){
                iDAO.add(itensRepublic);
            } else {
                iDAO.update(itensRepublic);
            }
        }


        
        setVisible(false);

    }//GEN-LAST:event_btSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btSaveActionPerformed(null);
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItensRepublicFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItensRepublicFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItensRepublicFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItensRepublicFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItensRepublicFrmRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSave;
    private javax.swing.JCheckBox cbResponsability;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblStudent;
    // End of variables declaration//GEN-END:variables
}
