/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.screen;

import br.meal.Meal;
import br.meal.MealDAO;
import br.menu.Menu;
import br.menu.MenuDAO;
import br.util.UserActive;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author pelusb
 */
public class MenuFrmRegister extends javax.swing.JDialog {

    private Menu menu;

    /**
     * Creates new form RegisterStudent
     */
    public MenuFrmRegister() {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setTitle("Cadastro de Cardápio");
        this.menu = new Menu();
        insertMeals();
        
        Date date = new Date();
        SimpleDateFormat dfdtDate;
        dfdtDate = new SimpleDateFormat("dd/MM/yyyy");
        tfDate.setText(dfdtDate.format(date));
    }

    public MenuFrmRegister(Menu menu) {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setTitle("Edição de Cardápio ["+menu.getDescription()+"]");
        insertMeals();
        this.menu = menu;
        tfDesc.setText(menu.getDescription());
        
        if (menu.getDate() != null) {
            Date date = menu.getDate();
            SimpleDateFormat dfdtDate;
            dfdtDate = new SimpleDateFormat("dd/MM/yyyy");
            tfDate.setText(dfdtDate.format(date));
        }
        
        if (this.menu.getMeal()!= null) {
            cbMeal.setSelectedItem(menu.getMeal());
        }
        
    }
    
    public void insertMeals() {
        cbMeal.removeAllItems();
        cbMeal.addItem("-");

        MealDAO mdao = new MealDAO();
        List<Meal> list = mdao.list("campus", UserActive.returnCampus(),"description");

        for (int i = 0; i < list.size(); i++) {
            cbMeal.addItem(list.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDesc = new javax.swing.JTextArea();
        tfDate = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        cbMeal = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/Save_37110.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/forceexit_103817.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Data: *");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        tfDesc.setColumns(20);
        tfDesc.setRows(5);
        jScrollPane1.setViewportView(tfDesc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, -1));

        try {
            tfDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDate.setToolTipText("Informe a data de nascimento");
        tfDate.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        tfDate.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        tfDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDateKeyPressed(evt);
            }
        });
        getContentPane().add(tfDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Descrição: *");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 17, -1, -1));

        cbMeal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbMeal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 210, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Refeição:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if (tfDesc.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe a Descrição!");
            tfDesc.requestFocus();
            return;
        }
        if (tfDate.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(rootPane, "Informe da data!");
            tfDate.requestFocus();
            return;
        }
        if (cbMeal.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(rootPane, "Informe a refeição!");
            cbMeal.requestFocus();
            return;
        }
        
        String date = tfDate.getText();
        try {
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date data;
            data = new java.util.Date(fmt.parse(date).getTime());
            menu.setDate(data);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Formata da dáta é inválido!", "IFCE", 
                    JOptionPane.ERROR_MESSAGE);
        }

        menu.setDescription(tfDesc.getText());
        menu.setCampus(UserActive.returnCampus());
        menu.setMeal((Meal) cbMeal.getSelectedItem());

        MenuDAO mDAO = new MenuDAO();
        menu.setCampus(UserActive.returnCampus());
        if (menu.getId() == null) {
            if(mDAO.checkExists("date", menu.getDate(), "meal", menu.getMeal()).size()>0){
                JOptionPane.showMessageDialog(rootPane, "Já existe um cardápio para essa refeição", "IFCE", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            mDAO.add(menu);
        } else {
            mDAO.update(menu);
        }
        setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDateKeyPressed
        
    }//GEN-LAST:event_tfDateKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrmRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbMeal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField tfDate;
    private javax.swing.JTextArea tfDesc;
    // End of variables declaration//GEN-END:variables
}
