/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.screen;

import br.config.Config;
import br.config.ConfigDAO;
import br.course.Course;
import br.course.CourseDAO;
import br.meal.Meal;
import br.meal.MealDAO;
import br.shift.Shift;
import br.shift.ShiftDAO;
import br.util.ConnectionFactory;
import br.util.Util;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.Hibernate;

/**
 *
 * @author pelusb
 */
public class ReportTotalMealsByPeriod extends javax.swing.JDialog {

    /**
     * Creates new form RegisterStudent
     */
    public ReportTotalMealsByPeriod() {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setTitle("Total de Refeições");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btPrint = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        edDateInitial = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        edDateEnd = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btPrint.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/printerprint_9416.png"))); // NOI18N
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/forceexit_103817.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        try {
            edDateInitial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edDateInitial.setToolTipText("Informe a data de nascimento");
        edDateInitial.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        edDateInitial.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        edDateInitial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edDateInitialKeyPressed(evt);
            }
        });
        getContentPane().add(edDateInitial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Data Inicial: *");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        try {
            edDateEnd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edDateEnd.setToolTipText("Informe a data de nascimento");
        edDateEnd.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        edDateEnd.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        edDateEnd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edDateEndKeyPressed(evt);
            }
        });
        getContentPane().add(edDateEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 150, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Data Final: *");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        if (edDateInitial.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(rootPane, "Informe a data inicial.");
            edDateInitial.requestFocus();
            return;
        }

        if (edDateEnd.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(rootPane, "Informe a data final.");
            edDateEnd.requestFocus();
            return;
        }

        String sql = "";
        String dataInicial = "", dataFinal = "";
        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(format.parse(edDateInitial.getText()).getTime());
            dataInicial = String.valueOf(data);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(format.parse(edDateEnd.getText()).getTime());
            dataFinal = String.valueOf(data);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        sql += "where s.date between '" + dataInicial + "' and '"
                + dataFinal + "' group by s.date, m.id "
                + "order by date";

        //pega dados das configurações
        Config config = null;
        ConfigDAO dao = new ConfigDAO();
        List<Config> list = dao.list();
        if (list != null) {
            if (list.size() > 0) {
                config = list.get(0);
            }
        }

        // TODO add your handling code here:
        JasperReport pathjrxml;
        HashMap parametros = new HashMap();
        parametros.put("sql", sql);
        Connection connection = new ConnectionFactory().getConnection();
        try {
            JDialog viewer = new JDialog(new javax.swing.JFrame(), "Visualização do Relatório", true);
            viewer.setSize(1200, 600);
            viewer.setLocationRelativeTo(null);
            viewer.setModal(true);
            //String caminho = Util.retornaCaminhoApp()+ config.getPathReport() + "summaryMeals.jrxml";
            //JOptionPane.showMessageDialog(rootPane, caminho);
            pathjrxml = JasperCompileManager.compileReport("src/br/report/summaryMeals.jasper");
            JasperPrint printReport = JasperFillManager.fillReport(pathjrxml, parametros,
                    connection);
            JasperViewer jv = new JasperViewer(printReport, false);
            viewer.getContentPane().add(jv.getContentPane());
            viewer.setVisible(true);
            //JasperExportManager.exportReportToPdfFile(printReport, "src/relatorios/RelAcervo.pdf");

            //jv.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "IFCE", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(ReportTotalMealsByPeriod.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btPrintActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void edDateInitialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edDateInitialKeyPressed
        verifyPressedEnter(evt);
    }//GEN-LAST:event_edDateInitialKeyPressed

    private void edDateEndKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edDateEndKeyPressed
        verifyPressedEnter(evt);
    }//GEN-LAST:event_edDateEndKeyPressed

    public void verifyPressedEnter(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btPrintActionPerformed(null);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportTotalMealsByPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportTotalMealsByPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportTotalMealsByPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportTotalMealsByPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportTotalMealsByPeriod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPrint;
    private javax.swing.JFormattedTextField edDateEnd;
    private javax.swing.JFormattedTextField edDateInitial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
