/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.screen;

import br.allowsmd.StudentAllowMealDayDAO;
import br.republic.ItensRepublic;
import br.republic.ItensRepublicDAO;
import br.republic.ItensRepublicTableModel;
import br.republic.Republic;
import br.republic.RepublicDAO;
import br.student.Student;
import br.student.StudentDAO;
import br.util.FormatSizeColJTable;
import br.util.UserActive;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author pelusb
 */
public class RepublicFrmRegister extends javax.swing.JDialog {

    private Republic republic;
    private List<ItensRepublic> itens = new ArrayList<ItensRepublic>();

    /**
     * Creates new form RegisterStudent
     */
    public RepublicFrmRegister() {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setTitle("Cadastro de República");
        insertStudent();
        this.republic = new Republic();
        //this.shift.setMeals(new ArrayList<Meal>());
        //insertListStudentsResponsability(shift.getMeals());
        
        cbStudent.setEnabled(false);
        btAdd.setEnabled(false);
        tbRepublic.setEnabled(false);
        btDelete.setEnabled(false);
    }

    public RepublicFrmRegister(Republic republic) {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setTitle("Edição de República [" + republic.getDescription() + "]");
        insertStudent();
        this.republic = republic;
        tfDesc.setText(republic.getDescription());
        tfAddress.setText(republic.getAddress());
        tfCity.setText(republic.getCity());
        tfNeighbohood.setText(republic.getNeighborhood());
        tfOwner.setText(republic.getOwnerRepublic());
        tfValue.setText(String.valueOf(republic.getValueRepublic()));
        /*
        if(republic.getItensRepublic()==null){
            republic.setItensRepublic(new ArrayList<ItensRepublic>());
        }*/
        
        preencheTabela(republic);
    }

    
    public void insertStudent() {
        cbStudent.removeAllItems();
        cbStudent.addItem("-");

        StudentDAO mdao = new StudentDAO();
        List<Student> list = mdao.list("campus", UserActive.returnCampus(), "name");
        
        list = new ArrayList(new HashSet(list));
        Collections.sort(list);
        for (int i = 0; i < list.size(); i++) {
            cbStudent.addItem(list.get(i));
        }
    }
    
    public void preencheTabela(Republic republic) {
        /*ItensRepublicTableModel ptm = new ItensRepublicTableModel(republic.getItensRepublic());
        tbRepublic.setModel(ptm);*/
        
        ItensRepublicDAO rDAO = new ItensRepublicDAO();
        if (republic == null) {
            List<ItensRepublic> list = new ArrayList<ItensRepublic>();
            list = new ArrayList(new HashSet(list));
            Collections.sort(list);
            ItensRepublicTableModel ptm = new ItensRepublicTableModel(list);
            tbRepublic.setModel(ptm);
        } else {
            List<ItensRepublic> list = rDAO.checkExists("republic", republic);
            list = new ArrayList(new HashSet(list));
            Collections.sort(list);
            ItensRepublicTableModel ptm = new ItensRepublicTableModel(list);
            tbRepublic.setModel(ptm);
        }

        FormatSizeColJTable.packColumns(tbRepublic, 1);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfDesc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cbStudent = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRepublic = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNeighbohood = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        tfOwner = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfDesc.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(tfDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 320, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Descrição: *");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btSave.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/Save_37110.png"))); // NOI18N
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        btCancel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/forceexit_103817.png"))); // NOI18N
        btCancel.setToolTipText("");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbStudent.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbStudent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbStudent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbStudentKeyPressed(evt);
            }
        });
        jPanel1.add(cbStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 400, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Estudante: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/new-file_40454.png"))); // NOI18N
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        jPanel1.add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 50, -1));

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/delete_peq.png"))); // NOI18N
        btDelete.setToolTipText("Remover Refeição");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 40, 40));

        tbRepublic.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tbRepublic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbRepublic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRepublicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbRepublicMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tbRepublic);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 590, 170));

        jLabel8.setText("** Clique duas vezes para editar.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 226, 320, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 640, 250));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Cidade: *");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        tfCity.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(tfCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 160, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Bairro: *");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        tfNeighbohood.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(tfNeighbohood, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 160, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Endereço: *");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        tfAddress.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(tfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 310, -1));

        tfOwner.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(tfOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 170, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Proprietário: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Valor: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        tfValue.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(tfValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:

        if (tfDesc.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe a Descrição!");
            tfDesc.requestFocus();
            return;
        }

        if (tfCity.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe a Cidade!");
            tfCity.requestFocus();
            return;
        }

        if (tfNeighbohood.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Bairro!");
            tfNeighbohood.requestFocus();
            return;
        }

        if (tfAddress.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Endereço!");
            tfAddress.requestFocus();
            return;
        }

        
       

        
        if (!tfValue.getText().equals("")) {
            Double valueRepublic = null;
            try {
                valueRepublic = Double.parseDouble(tfValue.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Formato do Valor errado!.");
            }
            republic.setValueRepublic(valueRepublic);
        }
        RepublicDAO cDAO = new RepublicDAO();
       
        republic.setDescription(tfDesc.getText());
        republic.setAddress(tfAddress.getText());
        republic.setCity(tfCity.getText());
        republic.setNeighborhood(tfNeighbohood.getText());
        republic.setOwnerRepublic(tfOwner.getText());
        
        republic.setCampus(UserActive.returnCampus());
        if (republic.getId() == null) {
            cDAO.add(republic);
        } else {
            cDAO.update(republic);
        }
        setVisible(false);

    }//GEN-LAST:event_btSaveActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        if (cbStudent.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Estudante.");
            return;
        }
        ItensRepublicDAO irDAO = new ItensRepublicDAO();
        Student stSelected = (Student) cbStudent.getSelectedItem();
        
        //verifica se estudante faz parte da republica
        List<ItensRepublic> itensRepublicList = irDAO.checkExists("republic", republic, "student", stSelected);
        if(itensRepublicList!=null){
            if(itensRepublicList.size()>0){
                JOptionPane.showMessageDialog(rootPane, "O estudante ["+stSelected.getName()+"] \njá faz parte dessa república." );
                return ;
            }
        }
        
        //verifica se estudante não está cadastrado em outra republica
        itensRepublicList = irDAO.checkExists("student", stSelected);
        if(itensRepublicList!=null){
            if(itensRepublicList.size()>0){
                JOptionPane.showMessageDialog(rootPane, "O estudante ["+stSelected.getName()
                        +"] \njá faz parte de outra república ["+itensRepublicList.get(0).getRepublic().getDescription()+"]." );
                return ;
            }
        }
        
        
        ItensRepublic iRepublic = new ItensRepublic();
        iRepublic.setRepublic(republic);
        iRepublic.setStudent(stSelected);

        ItensRepublicFrmRegister irfr = new ItensRepublicFrmRegister(iRepublic);
        irfr.setVisible(true);
        
        preencheTabela(republic);
       
    }//GEN-LAST:event_btAddActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
       if (tbRepublic.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha da tabela!");
        } else {
            ItensRepublicTableModel ptm = (ItensRepublicTableModel) tbRepublic.getModel();
            ItensRepublic select = ptm.getItensRepublic(tbRepublic.getSelectedRow());
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o estudante [" + select.getStudent().getName() + "] "
                    + "da república ["+select.getRepublic().getDescription()+"]? "
                    + "\nOBS: Será excluída todas as permissão para todas as refeições.",
                    "Excluir Estudante", JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                
                //exclui permissoes
                StudentAllowMealDayDAO samDAO = new StudentAllowMealDayDAO();
                samDAO.executeSQL("delete from allowstudenmealday where student_id="+select.getStudent().getId());
                
                ItensRepublicDAO rDAO = new ItensRepublicDAO();
                try {
                    rDAO.remove(select);
                } catch (Exception ex) {
                      JOptionPane.showMessageDialog(rootPane, "Item de república não pode ser excluído!");
                }
                preencheTabela(republic);
            }

        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void tbRepublicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRepublicMouseClicked
        if(evt.getClickCount() == 2){
            ItensRepublicTableModel ptm = (ItensRepublicTableModel) tbRepublic.getModel();
            ItensRepublic select = ptm.getItensRepublic(tbRepublic.getSelectedRow());
            ItensRepublicFrmRegister irfr = new ItensRepublicFrmRegister(select);
            irfr.setVisible(true);
            
            preencheTabela(republic);
        }

    }//GEN-LAST:event_tbRepublicMouseClicked

    private void tbRepublicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRepublicMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRepublicMouseEntered

    private void cbStudentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbStudentKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btAddActionPerformed(null);
        }
    }//GEN-LAST:event_cbStudentKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RepublicFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RepublicFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RepublicFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RepublicFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepublicFrmRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox cbStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbRepublic;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfCity;
    private javax.swing.JTextField tfDesc;
    private javax.swing.JTextField tfNeighbohood;
    private javax.swing.JTextField tfOwner;
    private javax.swing.JTextField tfValue;
    // End of variables declaration//GEN-END:variables
}
