/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.screen;

import br.allowsmd.StudentAllowMealDay;
import br.allowsmd.StudentAllowMealDayDAO;
import br.meal.Meal;
import br.meal.MealDAO;
import br.student.Student;
import br.student.StudentDAO;
import java.math.BigInteger;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author pelusb
 */
public class StudentAllowMealRegisterFrm extends javax.swing.JDialog {

    private StudentAllowMealDay stAllowMealDay;

    /**
     * Creates new form RegisterStudent
     */
    public StudentAllowMealRegisterFrm() {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setTitle("Cadastro de Refeição");
        insertMeals();
        this.stAllowMealDay = new StudentAllowMealDay();
    }

    public StudentAllowMealRegisterFrm(StudentAllowMealDay stAllowMealDay) {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setTitle("Permissão para Refeições - " + stAllowMealDay.getStudent().getName());
        insertMeals();
        this.stAllowMealDay = stAllowMealDay;
        if (stAllowMealDay.getId() != null) {
            cbMeal.setSelectedItem(stAllowMealDay.getMeal());
            cbMonday.setSelected(stAllowMealDay.isMonday());
            cbTuesday.setSelected(stAllowMealDay.isTuesday());
            cbWednesday.setSelected(stAllowMealDay.isWednesday());
            cbThusday.setSelected(stAllowMealDay.isThursday());
            cbFriday.setSelected(stAllowMealDay.isFriday());
            cbSaturday.setSelected(stAllowMealDay.isSaturday());
        }

    }

    public void insertMeals() {
        cbMeal.removeAllItems();
        cbMeal.addItem("-");

        MealDAO mdao = new MealDAO();
        List<Meal> list = mdao.list("description");

        for (int i = 0; i < list.size(); i++) {
            cbMeal.addItem(list.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbMeal = new javax.swing.JComboBox();
        cbTuesday = new javax.swing.JCheckBox();
        cbSaturday = new javax.swing.JCheckBox();
        cbMonday = new javax.swing.JCheckBox();
        cbWednesday = new javax.swing.JCheckBox();
        cbThusday = new javax.swing.JCheckBox();
        cbFriday = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/Save_37110.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/forceexit_103817.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Refeição:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        cbMeal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbMeal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 340, -1));

        cbTuesday.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbTuesday.setText("Terça");
        getContentPane().add(cbTuesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        cbSaturday.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbSaturday.setText("Sábado");
        getContentPane().add(cbSaturday, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        cbMonday.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbMonday.setText("Segunda");
        getContentPane().add(cbMonday, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        cbWednesday.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbWednesday.setText("Quarta");
        getContentPane().add(cbWednesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        cbThusday.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbThusday.setText("Quinta");
        getContentPane().add(cbThusday, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        cbFriday.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbFriday.setText("Sexta");
        getContentPane().add(cbFriday, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if (cbMeal.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Informe a Refeição!");
            cbMeal.requestFocus();
            return;
        }

        StudentAllowMealDayDAO mDAO = new StudentAllowMealDayDAO();

        stAllowMealDay.setMeal((Meal) cbMeal.getSelectedItem());
        stAllowMealDay.setMonday(cbMonday.isSelected());
        stAllowMealDay.setTuesday(cbTuesday.isSelected());
        stAllowMealDay.setWednesday(cbWednesday.isSelected());
        stAllowMealDay.setThursday(cbThusday.isSelected());
        stAllowMealDay.setFriday(cbFriday.isSelected());
        stAllowMealDay.setSaturday(cbSaturday.isSelected());

        if (stAllowMealDay.getId() == null) {
            StudentAllowMealDay objTest = mDAO.checkStudentMeal(stAllowMealDay.getStudent(),
                    (Meal) cbMeal.getSelectedItem());
            if (objTest != null) {
                JOptionPane.showMessageDialog(rootPane, "Essa refeição já foi \n cadastrada para esse aluno.");
                return;
            }

            mDAO.add(stAllowMealDay);
        } else {
            mDAO.update(stAllowMealDay);
        }
        setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentAllowMealRegisterFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentAllowMealRegisterFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentAllowMealRegisterFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentAllowMealRegisterFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentAllowMealRegisterFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbFriday;
    private javax.swing.JComboBox cbMeal;
    private javax.swing.JCheckBox cbMonday;
    private javax.swing.JCheckBox cbSaturday;
    private javax.swing.JCheckBox cbThusday;
    private javax.swing.JCheckBox cbTuesday;
    private javax.swing.JCheckBox cbWednesday;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
