/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.screen;

import br.campus.Campus;
import br.campus.CampusDAO;
import br.course.Course;
import br.course.CourseDAO;
import br.user.User;
import br.user.UserDAO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author pelusb
 */
public class UserFrmRegister extends javax.swing.JDialog {

    private User user;

    /**
     * Creates new form RegisterStudent
     */
    public UserFrmRegister() {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setTitle("Cadastro de Usuário");
        insertCampus();
        this.user = new User();
        cbActive.setSelected(true);
        cmbType.setSelectedIndex(0);
    }

    public UserFrmRegister(User user) {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setTitle("Edição de Usuário ["+user.getName()+"");
        insertCampus();
        this.user = user;
        tfName.setText(user.getName());
        tfLogin.setText(user.getLogin());
        tfLogin.setEnabled(false);
        cbActive.setSelected(user.isActive());
        cmbType.setSelectedItem(user.getTipo());
        cmbCampus.setSelectedItem(user.getCampus());
    }

    public void insertCampus() {
        cmbCampus.removeAllItems();
        cmbCampus.addItem("-");

        CampusDAO mdao = new CampusDAO();
        List<Campus> list = mdao.list("description");

        for (int i = 0; i < list.size(); i++) {
            cmbCampus.addItem(list.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        tfPass = new javax.swing.JPasswordField();
        tfConPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbActive = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox();
        cmbCampus = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 500, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Nome: *");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/Save_37110.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/forceexit_103817.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Tipo: *");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        tfLogin.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(tfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 500, -1));

        tfPass.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(tfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 500, -1));

        tfConPass.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(tfConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 500, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Login: *");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Senha: *");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        cbActive.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbActive.setText("Ativo");
        getContentPane().add(cbActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Confirmar Senha: *");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        cmbType.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "ASSIS_ESTU", "RECEPCAO" }));
        getContentPane().add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 280, -1));

        cmbCampus.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cmbCampus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "ASSIS_ESTU", "RECEPCAO" }));
        getContentPane().add(cmbCampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 280, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Campus: *");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if (tfName.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Nome!");
            tfName.requestFocus();
            return;
        }

        if (tfLogin.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Login!");
            tfLogin.requestFocus();
            return;
        }

        if (tfPass.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe a senha!");
            tfPass.requestFocus();
            return;
        }

        if (tfConPass.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe a confirmação da senha!");
            tfConPass.requestFocus();
            return;
        }

        if (!tfConPass.getText().equals(tfPass.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Senhas não conferem!");
            tfPass.requestFocus();
            return;
        }

        if (cmbType.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecine o tipo!");
            cmbType.requestFocus();
            return;
        }

        if (cmbCampus.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecine o Campus!");
            cmbCampus.requestFocus();
            return;
        }
        UserDAO uDAO = new UserDAO();

        user.setName(tfName.getText());
        user.setLogin(tfLogin.getText());
        user.setSenha(tfPass.getText());
        user.setTipo(cmbType.getSelectedItem().toString());
        user.setCampus((Campus) cmbCampus.getSelectedItem());
        user.setActive(cbActive.isSelected());

        
        if (user.getId() == null) {
            //verifica se ja possui login cadastrado
            List<User> userExists = uDAO.checkExists("login", tfLogin.getText());
            if (userExists != null) {
                if (userExists.size() > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Login já cadastrado!");
                    tfLogin.requestFocus();
                    return;
                }
            }
            user.setActive(true);
            uDAO.add(user);
        } else {
            uDAO.update(user);
        }
        setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrmRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbActive;
    private javax.swing.JComboBox cmbCampus;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField tfConPass;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPass;
    // End of variables declaration//GEN-END:variables
}
